<?php

namespace Abroad\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FunGroupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FunGroupRepository extends EntityRepository
{
}
