<?php

namespace Abroad\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * InvitationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InvitationRepository extends EntityRepository
{
    
    public function isInvited($senderId, $recipientId) {
	    $qb = $this->createQueryBuilder('i')
		    ->select('i.senderId', 'i.recipientId', 'i.id')
		    ->where('(i.senderId = :senderId AND i.recipientId = :recipientId AND i.status = false) OR '
			    . '(i.senderId = :recipientId AND i.recipientId = :senderId AND i.status = false)')
		    ->setParameter('senderId', $senderId)
		    ->setParameter('recipientId', $recipientId);

	    return $qb->getQuery()
		    ->getResult();
    }
    
    public function checkInvitations($recipientId) {
	$qb = $this->createQueryBuilder('i')
		->select('i')
		->where('i.recipientId = :recipientId AND i.status = false')
		->setParameter('recipientId', $recipientId);
	
	return $qb->getQuery()
		->getResult();
    }
    
    public function acceptInvitation($senderId, $recipientId) {
	$qb = $this->createQueryBuilder('i')
		->update('AbroadUserBundle:Invitation','i')
		->set('i.status', TRUE)
		->where('i.senderId = :senderId AND i.recipientId = :recipientId')
		->setParameters(array (
		    'senderId'=>$senderId,
		    'recipientId'=>$recipientId
		));
	
		return $qb->getQuery()
			->getResult();
			
//			var_dump($aa);			die();
    }
    
    public function delInvitation($senderId, $recipientId) {
	$qb = $this->createQueryBuilder('i')
		->delete('AbroadUserBundle:Invitation','i')
		->where('(i.senderId = :senderId AND i.recipientId = :recipientId) OR'
                        . '(i.senderId = :recipientId AND i.recipientId = :senderId)')
		->setParameters(array (
		    'senderId'=>$senderId,
		    'recipientId'=>$recipientId
		));
	
		return $qb->getQuery()
			->execute();
			
//			var_dump($aa);			die();
    }
    
    
}
