<?php

namespace Abroad\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    
//    /**
//     * @param string $role
//     *
//     * @return array
//     */
//    public function findByRole($role)
//    {
//	$qb = $this->_em->createQueryBuilder();
//	$qb->select('u')
//	    ->from($this->_entityName, 'u')
//	    ->where('u.roles LIKE :roles')
//	    ->setParameter('roles', '%"'.$role.'"%');
//
//	return $qb->getQuery()->getResult();
//    }
//
//
//    /**
//     * @param string $role
//     *
//     * @return array
//     */
//    public function findByRole($role)
//    {
//	$qb = $this->_em->createQueryBuilder();
//	$qb->select('u')
//	    ->from($this->_entityName, 'u')
//	    ->join('u.groups', 'g')
//	    ->where($qb->expr()->orX(
//		$qb->expr()->like('u.roles', ':roles'),
//		$qb->expr()->like('g.roles', ':roles')
//	    ))
//	    ->setParameter('roles', '%"'.$role.'"%');
//
//	return $qb->getQuery()->getResult();
//    }
    
    
}
