fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    
fos_user_group:
    resource: "@FOSUserBundle/Resources/config/routing/group.xml"
    prefix: /group
    
#fos_user_group:
#    resource: "@AbroadUserBundle/Resources/config/routing/group.xml"
#    prefix: /group

abroad_blog:
    resource: "@AbroadBlogBundle/Resources/config/routing.yml"
    prefix:   /

abroad_crud:
    resource: "@AbroadCrudBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
