<?php

namespace Abroad\BlogBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends EntityRepository
{
    public function getCommentsForBlog($blogId, $approved = true) {
	$qb = $this->createQueryBuilder('c')
		->select('c')
		->where('c.blog = :blog_id')
		->addOrderBy('c.created', 'DESC')
		->setParameter('blog_id', $blogId);
	
/////////// DQL
//	$qb = $this->createQuery(
//		'SELECT b'
//		. 'FROM AbroadBlogBundle:Comment c'
//		. 'WHERE c.blog = :blog_id'
//		. 'ORDER BY c.created DESC'
//		)->setParameter('blog_id', $blogId);
	if (false === is_null($approved))
	    $qb->andWhere('c.approved = :approved')
		->setParameter('approved', $approved);
	
	
	return $qb->getQuery()
		    ->getResult();
	
	
    }
    
    public function getLatestComments($limit = 10) {
	$qb = $this->createQueryBuilder('c')
		->select('c')
		->addOrderBy('c.created', 'DESC');
	
	if (FALSE === is_null($limit)){
	    $qb->setMaxResults($limit);
	}
	
	return $qb->getQuery()->getResult();
    }
}
