abroad_user_homepage:
    path:     /hello/{name}
    defaults: { _controller: AbroadUserBundle:Default:index }

#fos_user_group_list:
#    pattern:   /list
#    defaults: {_controller: AbroadUserBundle:Group:list}
#    requeriments:
#        _method: GET



#    <route id="fos_user_group_list" path="/list" methods="GET">
#        <default key="_controller">FOSUserBundle:Group:list</default>
#    </route>