#abroad_user_homepage:
#    path:     /hello/{name}
#    defaults: { _controller: AbroadUserBundle:Default:index }

#abroad_user_fungroup_new:
#    pattern: /new
#    defaults: { _controller: AbroadUserBundle:FunGroup:new}
#    requirements:
#        _method: GET
        
abroad_user_fungroup_new:
    pattern: /fungroup/new
    defaults: {_controller: AbroadUserBundle:FunGroup:new}
    requirements:
        _method: GET|POST

abroad_user_fungroup_list:
    pattern: /fungroup/list
    defaults: {_controller: AbroadUserBundle:FunGroup:list}
    requirements:
        _method: GET
        
abroad_user_fungroup_show:
    pattern: /fungroup/{id}/{slug}
    defaults: {_controller: AbroadUserBundle:FunGroup:show}
    requirements:
        _method: GET
        id: \d+
        
abroad_user_users_list:
    pattern: /users/list
    defaults: {_controller: AbroadUserBundle:Friends:listUsers}
    requirements:
        _method: GET
        
abroad_user_profile_show:
    pattern: /user/{id}
    defaults: {_controller: AbroadUserBundle:Profile:showOne}
    requirements:
        _method: GET
        id: \d+
    
abroad_user_add_friend:
    pattern: /addfriend/{id}
    defaults: {_controller: AbroadUserBundle:Friends:addFriend}
    requirements:
        _method: GET
        id: \d+

abroad_user_un_friend:
    pattern: /unfriend/{id}
    defaults: {_controller: AbroadUserBundle:Friends:removeFriend}
    requirements:
        _method: GET
        id: \d+

abroad_user_set_friend_invitation:
    pattern: /setinvitation/{id}
    defaults: {_controller: AbroadUserBundle:Friends:setFriendInvitation}
    requirements:
        _method: GET
        id: \d+
        
abroad_list_invitations:
    pattern: /listinvitations
    defaults: {_controller: AbroadUserBundle:Friends:listFriendInvitations}
    requirements:
        _method: GET

abroad_accept_invitation:
    pattern: /accept/{senderId}
    defaults: {_controller: AbroadUserBundle:Friends:acceptFriendInvitation}
    requirements:
        _method: GET
        
abroad_my_friends:
    pattern: /myfriends
    defaults: {_controller: AbroadUserBundle:Friends:listFriends}
        
#fos_user_group_list:
#    pattern:   /list
#    defaults: {_controller: AbroadUserBundle:Group:list}
#    requirements:
#        _method: GET



#    <route id="fos_user_group_list" path="/list" methods="GET">
#        <default key="_controller">FOSUserBundle:Group:list</default>
#    </route>